# Generated by Django 4.2.24 on 2026-01-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='name',
            new_name='society_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apartment'),
        ),
    ]
