# Generated by Django 4.2.24 on 2026-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='expected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('delivery', 'Delivery'), ('service', 'Service Provider'), ('cab', 'Cab Driver')], max_length=20),
        ),
    ]
