# Generated by Django 4.2.24 on 2026-01-21 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='apartment',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.apartment'),
            preserve_default=False,
        ),
    ]
