# Generated by Django 4.2.24 on 2026-01-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='expected_at',
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vehicle_details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('delivery', 'Delivery'), ('daily_help', 'Daily Help')], max_length=20),
        ),
    ]
