# Generated by Django 4.2.24 on 2026-01-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_visitor_expected_at_visitor_expected_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='expected_date',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='expected_duration',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='expected_time',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('delivery', 'Delivery'), ('service', 'Service Provider'), ('cab', 'Cab Driver')], max_length=20),
        ),
    ]
