# Generated by Django 4.2.24 on 2026-01-21 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_apartment_society_name_userprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='core.society'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.society'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.society'),
        ),
    ]
