# Generated by Django 4.2.24 on 2026-01-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_apartment_society_alter_userprofile_society_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'status'], name='core_userpr_role_567b62_idx'),
        ),
    ]
