# Generated by Django 4.2.24 on 2026-01-22 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_emergencycontact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
