# Generated by Django 4.2.24 on 2026-01-22 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_alter_delivery_apartment_alter_delivery_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timing', models.CharField(help_text='e.g., 6 AM - 8 AM', max_length=100)),
                ('days', models.CharField(help_text='e.g., Mon-Sat', max_length=100)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 to 5 stars')),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hired_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.hiredservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.CharField(help_text='e.g., Nanded City, Sinhagad Road', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('full_address', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='service_providers/id_proof/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service_providers/photos/')),
                ('police_verification', models.BooleanField(default=False)),
                ('available_days', models.CharField(help_text='e.g., Mon-Fri, All Days', max_length=200)),
                ('preferred_timings', models.CharField(help_text='e.g., 6 AM - 10 AM, Evening', max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_hires', models.PositiveIntegerField(default=0)),
                ('active_clients', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='core.service')),
            ],
            options={
                'ordering': ['-rating', '-total_hires'],
            },
        ),
        migrations.AddField(
            model_name='hiredservice',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['area', 'city'], name='core_servic_area_53d5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['service', 'verification_status'], name='core_servic_service_0e47ea_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_available'], name='core_servic_is_avai_f30630_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hiredservice',
            unique_together={('resident', 'service_provider')},
        ),
    ]
