# Generated by Django 4.2.24 on 2026-01-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_checkpoint_visitorphoto_patrolround_incidentreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='entry_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
    ]
