# Generated by Django 4.2.24 on 2026-01-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_visitor_check_in_time_visitor_check_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='entry_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
    ]
