# Generated by Django 4.2.24 on 2026-01-29 09:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_notification_options_notification_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='number',
            new_name='registration_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('2wheeler', 'Two Wheeler'), ('4wheeler', 'Four Wheeler'), ('bicycle', 'Bicycle'), ('truck', 'Truck'), ('other', 'Other')], default='4wheeler', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='parking_slot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('apartment', 'registration_number')},
        ),
    ]
