# Generated by Django 4.2.24 on 2026-01-30 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereview',
            options={},
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='hired_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.hiredservice'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
