# Generated by Django 4.2.24 on 2026-02-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_notification_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('guard', 'Guard'), ('guard_admin', 'Guard Admin'), ('society_admin', 'Society Admin'), ('admin', 'Super Admin'), ('service_provider', 'Service Provider')], max_length=20),
        ),
    ]
