# Generated by Django 4.2.24 on 2026-02-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardshift',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
    ]
