# Generated by Django 4.2.24 on 2026-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_guardshift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardshift',
            name='assigned_checkpoints',
            field=models.ManyToManyField(blank=True, related_name='assigned_shifts', to='core.checkpoint'),
        ),
        migrations.AddField(
            model_name='guardshift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardshift',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
