# Generated by Django 4.2.24 on 2026-02-09 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_guardshift_assigned_checkpoints_guardshift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardshift',
            name='attendance_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardshift',
            name='attendance_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardshift',
            name='attendance_override',
            field=models.CharField(choices=[('auto', 'Auto (System)'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], default='auto', max_length=10),
        ),
    ]
