# Generated by Django 4.2.24 on 2026-02-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_leaverequest_guardadminchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardshift',
            name='shift_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
