# Generated by Django 4.2.24 on 2026-02-25 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0042_alter_visitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['status'], name='core_visito_status_581d96_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['created_at'], name='core_visito_created_568fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['apartment', 'status'], name='core_visito_apartme_64ad29_idx'),
        ),
    ]
