# Generated by Django 4.2.24 on 2026-03-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/covers/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hometown',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, help_text='Comma-separated list, e.g. Music, Travel, Cricket', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/photos/'),
        ),
    ]
